"""trash items

Revision ID: 2195e88c99a7
Revises: 188d830287df
Create Date: 2026-08-03 05:45:58.623572

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2195e88c99a7"
down_revision: str | None = "188d830287df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trash_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("instance", sa.String(), nullable=False),
        sa.Column("original_path", sa.String(), nullable=False),
        sa.Column("trash_path", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("episode_ids", sa.JSON(), nullable=False),
        sa.Column("trashed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('expired', 'deleted', 'restored')",
            name=op.f("ck_trash_items_outcome_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_trash_items_file_id_files")
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_trash_items_job_id_jobs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trash_items")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trash_items")
    # ### end Alembic commands ###
