"""initial schema

Revision ID: 8f4629404241
Revises: 
Create Date: 2026-08-02 16:49:59.679063

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f4629404241'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('history_watermark', sa.Integer(), nullable=True),
    sa.Column('backfill_cursor', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('sonarr_path', sa.String(), nullable=False),
    sa.Column('local_path', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('episode_ids', sa.JSON(), nullable=False),
    sa.Column('episode_file_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('download_id', sa.String(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=True),
    sa.Column('indexer', sa.String(), nullable=True),
    sa.Column('guid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'episode_file_id', name='uq_files_instance_episode_file')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('input_fingerprint', sa.String(), nullable=False),
    sa.Column('tool_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('probe', 'audio', 'subs', 'frames', 'transcript')", name='ck_assets_type'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frame_hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('algo', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('timestamps', sa.JSON(), nullable=False),
    sa.Column('hashes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('hold', 'pending', 'active', 'matched', 'quarantine', 'inconclusive', 'error', 'remediated')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phash_corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_hash_id', sa.Integer(), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episodes', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('auto', 'human')", name='ck_phash_corpus_source'),
    sa.ForeignKeyConstraint(['frame_hash_id'], ['frame_hashes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(), nullable=False),
    sa.Column('plugin_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('normalized', sa.JSON(), nullable=False),
    sa.Column('input_fingerprint', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'abstain', 'error')", name='ck_plugin_results_status'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plugin_results_input_fingerprint', 'plugin_results', ['input_fingerprint'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('s_claimed', sa.Float(), nullable=True),
    sa.Column('s_alt', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('proposed_action', sa.JSON(), nullable=True),
    sa.Column('remediation_log', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('human_ident', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('auto', 'human')", name='ck_verdicts_source'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdicts')
    op.drop_index('ix_plugin_results_input_fingerprint', table_name='plugin_results')
    op.drop_table('plugin_results')
    op.drop_table('phash_corpus')
    op.drop_table('jobs')
    op.drop_table('frame_hashes')
    op.drop_table('assets')
    op.drop_table('files')
    op.drop_table('instances')
    # ### end Alembic commands ###
